import type { Metadata } from 'next';
import { Inter, JetBrains_Mono } from 'next/font/google';
import { AppRouterCacheProvider } from '@mui/material-nextjs/v13-appRouter';
import { ThemeProvider } from '@mui/material';
import theme from '@/theme';
import './globals.css';
import { AuthProvider } from '@/context/AuthContext';

const inter = Inter({
	weight: ['300', '400', '500', '700'],
	subsets: ['latin'],
	variable: '--font-inter',
	display: 'swap',
});

const jetbrains_mono = JetBrains_Mono({
	weight: ['300', '400', '500', '700'],
	subsets: ['latin'],
	variable: '--font-jetbrain-mono',
	display: 'swap',
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html
			lang="pt-br"
			className={`${inter.variable} ${jetbrains_mono.variable}`}
		>
			<body className={`${inter.className} antialiased`}>
				<AppRouterCacheProvider options={{ enableCssLayer: true }}>
					<ThemeProvider theme={theme}>
						<AuthProvider>{children}</AuthProvider>
					</ThemeProvider>
				</AppRouterCacheProvider>
			</body>
		</html>
	);
}
